/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.summercoding.bank.ui;

import com.summercoding.bank.controlleur.Controleur;
import com.summerconding.bank.entities.Admin;
import com.summerconding.bank.entities.Utilisateur;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mbeyo
 */
public class JFrameHome extends javax.swing.JFrame {
    
      Controleur controleur = new Controleur();

    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAdmin = new javax.swing.JMenu();
        CreerAdmin = new javax.swing.JMenuItem();
        ListerAdmin = new javax.swing.JMenuItem();
        MenuUtilisateur = new javax.swing.JMenu();
        CreerUtilisateur = new javax.swing.JMenuItem();
        ListerUtitilisateur = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        CreerCompte = new javax.swing.JMenuItem();
        ListerCompte = new javax.swing.JMenuItem();
        MenuApropos = new javax.swing.JMenu();
        MenuAide = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        MenuAdmin.setText("Admin");
        MenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdminActionPerformed(evt);
            }
        });

        CreerAdmin.setText("Créer");
        CreerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerAdminActionPerformed(evt);
            }
        });
        MenuAdmin.add(CreerAdmin);

        ListerAdmin.setText("Lister");
        ListerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListerAdminActionPerformed(evt);
            }
        });
        MenuAdmin.add(ListerAdmin);

        jMenuBar1.add(MenuAdmin);

        MenuUtilisateur.setText("Utilisateur");

        CreerUtilisateur.setText("Créer");
        CreerUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerUtilisateurActionPerformed(evt);
            }
        });
        MenuUtilisateur.add(CreerUtilisateur);

        ListerUtitilisateur.setText("Lister");
        ListerUtitilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListerUtitilisateurActionPerformed(evt);
            }
        });
        MenuUtilisateur.add(ListerUtitilisateur);

        jMenuBar1.add(MenuUtilisateur);

        jMenu3.setText("Compte");

        CreerCompte.setText("Créer");
        CreerCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerCompteActionPerformed(evt);
            }
        });
        jMenu3.add(CreerCompte);

        ListerCompte.setText("Lister");
        jMenu3.add(ListerCompte);

        jMenuBar1.add(jMenu3);

        MenuApropos.setText("A Propos");
        jMenuBar1.add(MenuApropos);

        MenuAide.setText("Aide");
        jMenuBar1.add(MenuAide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdminActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_MenuAdminActionPerformed

    private void CreerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerAdminActionPerformed
        // TODO add your handling code here:
         new JFrameSaveAdmin().setVisible(true);
    }//GEN-LAST:event_CreerAdminActionPerformed

    private void ListerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListerAdminActionPerformed
          try {
              // TODO add your handling code here:
              /* Ajout Manuelle des données
              String[] columns = new String [] {
                  
                  "Id", "Nom", "Login"
              };
              
              String[][] datas = new String [][] {
                  
                  {"1","toto","toto"},
                  {"2","titi","titi"},
                  {"3","tata","tata"},
                  {"4","tata","tata"},
              };*/
              
              List<Admin> listAdmin = controleur.routeVersListAllAdmin();
              
              DefaultTableModel model = new DefaultTableModel();
              model.addColumn("Id");
              model.addColumn("Nom");
              model.addColumn("Login");
                
                for(Admin ad : listAdmin){
                    
                model.addRow(new String[] {ad.getIdadmin()+"", ad.getNom(), ad.getLogin()});    
                }
              
              Table.setModel(model);
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
              
               JOptionPane.showMessageDialog(null, "Veuiller conctater l'administrateur si le problème persiste ");
          }
    }//GEN-LAST:event_ListerAdminActionPerformed

    private void CreerUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerUtilisateurActionPerformed
        // TODO add your handling code here:
        
         new JFrameSaveUtilisateur().setVisible(true);
    }//GEN-LAST:event_CreerUtilisateurActionPerformed

    private void ListerUtitilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListerUtitilisateurActionPerformed
        // TODO add your handling code here:
        
           try {
              // TODO add your handling code here:
              /* Ajout Manuelle des données
              String[] columns = new String [] {
                  
                  "Id", "Nom", "Login"
              };
              
              String[][] datas = new String [][] {
                  
                  {"1","toto","toto"},
                  {"2","titi","titi"},
                  {"3","tata","tata"},
                  {"4","tata","tata"},
              };*/
              
              List<Compte> listCompte = controleur.routeVersListUtilisateur();
              
              DefaultTableModel model = new DefaultTableModel();
              model.addColumn("Id");
              model.addColumn("Solde");
                
                for(Utilisateur ad : listUtilisateur){
                    
                model.addRow(new String[] {ad.getidUser()+"", ad.getNom(), ad.getLogin()});    
                }
              
              Table.setModel(model);
          } catch (ClassNotFoundException ex) {
               Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
              
               JOptionPane.showMessageDialog(null, "Veuiller conctater l'administrateur si le problème persiste ");
          }
    }//GEN-LAST:event_ListerUtitilisateurActionPerformed

    private void CreerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerCompteActionPerformed
        // TODO add your handling code here:
        
         new JFrameSaveCompte().setVisible(true);
    }//GEN-LAST:event_CreerCompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CreerAdmin;
    private javax.swing.JMenuItem CreerCompte;
    private javax.swing.JMenuItem CreerUtilisateur;
    private javax.swing.JMenuItem ListerAdmin;
    private javax.swing.JMenuItem ListerCompte;
    private javax.swing.JMenuItem ListerUtitilisateur;
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenu MenuAide;
    private javax.swing.JMenu MenuApropos;
    private javax.swing.JMenu MenuUtilisateur;
    private javax.swing.JTable Table;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
